spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/jialiangjie/leyou-config.git
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: /leyou
    username: leyou
    password: leyou
management: #http://127.0.0.1:12000/actuator/bus-refresh #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh
server:
  port: 12000


