server:
  port: 8085
spring:
  application:
    name: user-service
  redis:
    host: 127.0.0.1
    port: 6379
  rabbitmq:
    host: 127.0.0.1
    username: leyou
    password: leyou
    virtual-host: /leyou
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql:///leyou-103?characterEncoding=utf-8

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka


logging:
  level:
    com.leyou: debug
ly:
  encoder:
    crypt:
      secret: ${random.uuid} # 随机的密钥，使用uuid
      strength: 10 # 加密强度4~31，决定了密码和盐加密时的运算次数，超过10以后加密耗时会显著增加